pipeline:
  name: build-push-deploy
  identifier: buildpushdeploy
  projectIdentifier: testgcp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: guthubconnectorviadelegate
        build: <+input>
  stages:
    - stage:
        name: build-and-push-to-dockerhub
        identifier: buildandpushtodockerhub
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: ccedockerhubconnector
                    repo: manu7827/harness-build-images
                    tags:
                      - 0.0.1
