pipeline:
  name: push to dockerhub
  identifier: push_to_dockerhub
  projectIdentifier: testgcp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: guthubconnectorviadelegate
        build: <+input>
  stages:
    - stage:
        name: push
        identifier: push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: ccedockerhubconnector
                    repo: manu7827/harness-build-images
                    tags:
                      - latest
