pipeline:
  name: push
  identifier: push
  projectIdentifier: testgcp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: guthubconnectorviadelegate
        build: <+input>
  stages:
    - stage:
        name: build-and-push-to-dockerhub
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: ccedockerhubconnector
                    repo: manu7827/harness-build-images
                    tags:
                      - latest
          caching:
            enabled: false
            paths: []
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: k8sdeploy
          environment:
            environmentRef: prepod
            gitBranch: main
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k8s
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
